### ISSUE TITLE
undercloud upload: role or config option

### ISSUE THREAD

**Issue by Toure** [redhat-openstack/ansible-role-tripleo-image-build#7]
A method in which a file location can used to upload files / directories onto a deployed undercloud instance. 

Example:

```
- name: undercloud fetch service.
  upload:
       src: "{{ path_to_files }}" or "{{ url }}"
       dest: "{{ upload_dir }}" 
```
